---

- hosts: all
  become: true
  tasks:

 
  - name: install apache2 & PHP package for Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes



  - name: install apache2 & PHP package for AlmaLinux
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes