---

- hosts: all
  become: true
  tasks:


  - name: install apache and php packagesfor Ubuntu
    package:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for Alma
    package:
      name:
        - httpd
        - php  
      state: latest
      update_cache: yes
    when: ansible_distribution == "AlmaLinux"
