---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS" 

  - name: install updates (CentOS)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"  

- hosts: web_servers
  become: true 
  tasks: 


  - name: install apache and php packagesfor Ubuntu
    package:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php packages for CentOS
    package:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"   

  - name: install samba package
    package:
      name: samba
      state: latest  

- hosts: name_servers
  become: true
  tasks:

  - name: install BIND9
    package:
      name:
        - bind9
      state: latest
    when: ansible_distribution == "Ubuntu"    
       
