- name: install apache and php packagesfor Ubuntu
  tags: apache,apache2,ubuntu
  apt:
    name: 
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install apache and php packages for AlmaLinux
  tags: apache,AlmaLinux,httpd
  dnf: 
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "AlmaLinux"

- name: start httpd (AlmaLinux)
  tags: apache,AlmaLinux,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "AlmaLinux"

- name: change e-mail address for admin
  tags: apache,AlmaLinux,httpd
  lineinfile: 
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin wzpoplaski@startmail.com
  when: ansible_distribution == "AlmaLinux"
  register: httpd

- name: restart httpd (AlmaLinux)
  tags: apache,AlmaLinux,httpd
  service:
    name: httpd
    state: restarted
  when: httpd.changed


- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html  
    dest: /var/www/html/index.html  
    owner: root
    group: root
    mode: 0644
