- name: install mariadb package (AlmaLinux)
  tags: AlmaLinux,db,mariadb
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "AlmaLinux"

- name: install mariadb package (Ubuntu)
  tags: db,mariadb,Ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"   
